server:
  port: 0

spring:
  application:
    name: auth-service
  config:
    import: "configserver:"

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs
  swagger-ui:
    path: /api/auth/swagger-ui.html