server:
  port: 0

spring:
  datasource:
    username: postgres
    password: 1111
    url: jdbc:postgresql://database:5432/postgres

openapi:
  service:
    title: auth-service doc
springdoc:
  openapi:
    service:
      version: 1.0.0
      url: http://api-gateway:8080/
  api-docs:
    path: /api/auth/v3/api-docs
  swagger-ui:
    path: /api/auth/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka