server:
  port: 0

spring:

  application:
    name: book-service
  config:
    import: "configserver:"

springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    path: /book-service/swagger-ui.html
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


