server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: ${GIT_URI}
          private-key: ${SSH_GIT_PRIVATE_KEY}
          ignore-local-ssh-settings: true
          force-pull: true
          search-paths: config

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false