server:
  port: 8888

spring:
  profiles:
    active: native # used if you want config from locals file (delete if you need configs from git)
  application:
    name: config-server


  cloud:
    config:
      server:
        native:
          search-locations: config
        git:
          clone-on-start: true
          uri: ${GIT_URI}
          private-key: ${SSH_GIT_PRIVATE_KEY}
          ignore-local-ssh-settings: true
          force-pull: true
          search-paths: config


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false