server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          clone-on-start: true
          uri: https://github.com/XD-cods/modsen-test-configs.git