server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    import: "optional:configserver:"

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config